# Generated by Django 5.2.5 on 2025-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nbr_copy',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
