# Generated by Django 5.2.5 on 2025-09-18 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_book_nbr_copy_alter_chat_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevu_depos', models.DateTimeField(null=True)),
                ('date_depos', models.DateTimeField(null=True)),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('amande_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('amande_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
